export const translations = {
  ru: {
    gameTitle: 'Arrow Shift', level: 'Уровень', restart: 'Заново', done: 'Готово', allDone: 'Все уровни пройдены', startOver: 'Сначала', next: 'Дальше', noMoves: 'Ходов нет', tryAgain: 'Заново', play: 'Играть', continue: 'Продолжить', levels: 'Уровни', levelsCount: 'уровней', home: 'Главная', sound: 'Звук', soundOn: 'Звук включён', soundOff: 'Звук выключен', locked: 'Уровень закрыт', allLevelsCompleted: 'Все уровни пройдены', firstHint: 'Нажми на свободную стрелку', shiftHint: 'Выход поворачивает стрелки в этой линии', pinnedHint: 'Закреплённые стрелки не поворачиваются', barrierHint: 'Препятствия блокируют путь', pathBroken: 'Путь оборвался', routeLooped: 'Маршрут зациклился', language: 'EN', arrow: 'Стрелка', pinned: 'закреплена', barrier: 'Препятствие', puzzles: 'Головоломки', route: 'Маршрут', rush: 'Спринт', run: 'Запустить', reset: 'Сбросить', routeComplete: 'Маршрут готов', routeFailed: 'Маршрут не построен', rotationLimit: 'Лимит поворотов', rotations: 'Поворотов', time: 'Время', score: 'Счёт', combo: 'Комбо', best: 'Рекорд', again: 'Ещё раз', bestResult: 'Лучший результат', fields: 'Полей', rushBonus: '+4с', rushHint: 'Убирай свободные стрелки', rushNewBest: 'Новый рекорд', unlockAfter: 'Откроется после уровня', start: 'Старт', target: 'Цель', direction: { up: 'вверх', right: 'вправо', down: 'вниз', left: 'влево' },
  },
  en: {
    gameTitle: 'Arrow Shift', level: 'Level', restart: 'Restart', done: 'Done', allDone: 'All levels complete', startOver: 'Start over', next: 'Next', noMoves: 'No moves', tryAgain: 'Try again', play: 'Play', continue: 'Continue', levels: 'Levels', levelsCount: 'levels', home: 'Home', sound: 'Sound', soundOn: 'Sound on', soundOff: 'Sound off', locked: 'Level locked', allLevelsCompleted: 'All levels complete', firstHint: 'Tap a free arrow', shiftHint: 'Exiting rotates arrows in this line', pinnedHint: "Pinned arrows don't rotate", barrierHint: 'Barriers block the path', pathBroken: 'Path broken', routeLooped: 'Route looped', language: 'RU', arrow: 'Arrow', pinned: 'pinned', barrier: 'Barrier', puzzles: 'Puzzles', route: 'Route', rush: 'Rush', run: 'Run', reset: 'Reset', routeComplete: 'Route complete', routeFailed: 'Route failed', rotationLimit: 'Rotation limit', rotations: 'Rotations', time: 'Time', score: 'Score', combo: 'Combo', best: 'Best', again: 'Again', bestResult: 'Best result', fields: 'Boards', rushBonus: '+4s', rushHint: 'Clear the free arrows', rushNewBest: 'New best', unlockAfter: 'Unlocks after level', start: 'Start', target: 'Target', direction: { up: 'up', right: 'right', down: 'down', left: 'left' },
  },
};

export function getText(language) {
  return translations[language] || translations.ru;
}
